//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zaloka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZalokaUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string utm_sourse { get; set; }
        public string utm_medium { get; set; }
        public string utm_campaign { get; set; }
        public string utm_content { get; set; }
        public Nullable<System.DateTime> NgayDangKi { get; set; }
        public string utm_term { get; set; }
    }
}
